### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by anafaraco01** [Team-07-Looney/looney-general#23]
# User Story
As a user, I want to be able to register so that I can gain access to my personalized application.

# Estimated Time
Estimated time: 4 day

# Definition of done: 
## User side: 
- The user can see the register form
- The user can insert their credentials
- The user can see that there is an error with the credentials in case the authentication is unsuccessful
- The user is redirected to a page different from the registration one when the authentication is successful

## Developer side:
- Registration request is sent to the api gateway and it redirects it to the user microservice to register the user 
If successful: 
- The new user is retrieved
- JWT token is created based on the id of the user
- Token is saved in a jwt cookie
Otherwise:
- Error is handled in correct manner

**Comment by DanielBartha** [comment]
Estimated time: 3 days
