### ISSUE TITLE
Design Guidelines

### ISSUE THREAD

**Issue by v-stamenova** [Team-07-Looney/looney-general#33]
### User story
As a user, I want the app to be consistent, so that I will not get confused while browsing the app.
### Definition of done
When the palett color, fonts, looney icon, forms, animation and styling are determined
### Estimated time
4 days
### Actual time
2 weeks

**Comment by anafaraco01** [comment]
Done: When the palett color, fonts, looney icon, forms, animation and styling are determined

**Comment by DanielBartha** [comment]
Estimated time: 1 week
